version: '3.8'

services:
  api:
    build: ./
    command: sh dev.sh
    volumes:
      - .//:/app/
    ports:
      - 8001:8000
    environment:
      - DB_PORT=5432
      - DB_NAME=api_posts
      - DB_USER=dev
      - DB_PASS=12345678
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

  db:
      image: postgres:alpine
      volumes:
        - postgres_db:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=dev
        - POSTGRES_PASSWORD=12345678
        - POSTGRES_DB=api_posts
      ports:
        - 8006:5432
      healthcheck:
        test: ["CMD-SHELL", "pg_isready", "-q", "-d", "api_posts", "-U", "dev" ]
        interval: 5s
        timeout: 5s
        retries: 5

volumes:
  postgres_db: